### ISSUE TITLE
UXTopic 传入下方 handlers

### ISSUE THREAD

**Issue by mingrui** [lattesir/uxapi#6]
```
okex.futures.public_trades:
    exchange_id: okex
    market_type: futures
    datatype: trade
    extrainfo: BTC/USD.CQ
```

hadlers 经常需要用到 UXTopics 内的信息，是否可以直接把 UXTopic 提供给 handlers 使用？

现在的一个 work around 是把 topic 当作 handlers parameter 传入:

```
pipeline = Pipeline([HuobiParseOrderBookDelta(topic), OrderBookDeltaToRedisStream(redis_client, 1000)])
```
